plugins {
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.micronaut.application") version "4.2.1"
}

version = "0.1"
group = "com.notesmaker"

// Set Micronaut version
micronaut {
    version "4.2.1"
}

repositories {
    mavenCentral()
    maven { url "https://repo.maven.apache.org/maven2" }
}

dependencies {
    implementation platform("io.micronaut.platform:micronaut-platform:4.2.1")
    annotationProcessor platform("io.micronaut.platform:micronaut-platform:4.2.1")
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    implementation("io.github.cdimascio:dotenv-java:2.3.0") 
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut:micronaut-jackson-databind")
    implementation("io.micronaut:micronaut-management")
    implementation("io.micronaut.micrometer:micronaut-micrometer-core")
    implementation("io.micronaut.micrometer:micronaut-micrometer-registry-prometheus")
    
    // ScyllaDB/Cassandra driver
    implementation("com.datastax.oss:java-driver-core:4.17.0")
    implementation("com.datastax.oss:java-driver-query-builder:4.17.0")
    
    // CORS support
    implementation("io.micronaut:micronaut-http-server-netty")
    
    compileOnly("org.graalvm.nativeimage:svm")
    
    runtimeOnly("ch.qos.logback:logback-classic")

    implementation("io.micronaut.cassandra:micronaut-cassandra")
}

application {
    mainClass.set("com.notesmaker.Application")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

graalvmNative.toolchainDetection = false

micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("com.notesmaker.*")
    }
} 
