apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-maker-config
  namespace: notes-maker
data:
  init-keyspace.cql: |
    CREATE KEYSPACE IF NOT EXISTS notes_maker
    WITH REPLICATION = {
        'class': 'NetworkTopologyStrategy',
        'DC1': 1
    };
    USE notes_maker;
    CREATE TABLE IF NOT EXISTS notes (
        id UUID PRIMARY KEY,
        title TEXT,
        content TEXT,
        created_at TIMESTAMP,
        updated_at TIMESTAMP
    );
